version: "3.9"

networks:
  backend:
    driver: "bridge"

services:

### MariaDB Server ########################################
  mariadb:
    container_name: mariadb_dev
    build:
        context: ./mariadb
        args:
          - MARIADB_VERSION=${MARIADB_VERSION}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    environment:
      - TZ=UTC
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend

### phpMyAdmin ###########################################
  phpmyadmin:
    container_name: pma_dev
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - backend

### PHP-FPM ##############################################
  php-fpm:
    container_name: php-fpm_dev
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    ports:
      - "${PHP_FPM_HOST}:${PHP_FPM_PORT}:9000"
    volumes:
      - ../:${APP_CODE_PATH_CONTAINER}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - backend

### NGINX Server #########################################
  nginx:
    container_name: nginx_dev
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:cached" #When using Docker Sync add `:nocopy`
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - backend
